services:
  postgres:
    image: postgres:16
    container_name: mule-pg
    environment:
      POSTGRES_DB: muledb
      POSTGRES_USER: mule
      POSTGRES_PASSWORD: mulepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mule -d muledb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
